[project]
name = "mod-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "anthropic>=0.49.0",
]
